cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.ViewCart.as_view(), name='view_cart'),
    path('add/<item_id>', views.add_to_cart, name='add_to_cart'),
    path('update/<item_id>', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>', views.remove_item, name='remove_item'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
]

products/urls.py
from django.urls import path

from . import views


app_name = 'products'
urlpatterns = [
    path('', views.LatestProducts.as_view(), name='latest'),
    path('category/<str:slug>', views.CategoryView.as_view(), name='category'),
    path('product/<slug>', views.ProductDetail.as_view(), name='product'),
    path('current_stock/', views.current_stock, name='current_stock'),
    path('search_results/', views.SearchResults.as_view(),
         name='search_results'),
]

profiles/urls.py
from django.urls import path

from . import views


app_name = 'profiles'
urlpatterns = [
     path('profile/', views.ProfileView.as_view(), name='profile'),
     path('edit_profile/', views.UpdateProfile.as_view(), name='edit_profile'),
     path('delete_account/', views.DeleteAccount.as_view(),
          name='delete_account'),
     path('order_history/<order_number>', views.OrderHistory.as_view(),
          name='order_history'),
     path('review_list/', views.ReviewList.as_view(), name='review_list'),
     path('edit_review/<pk>', views.EditReview.as_view(), name='edit_review'),
     path('delete_review/<pk>', views.DeleteReview.as_view(),
          name='delete_review'),
     path('user_recipes/', views.UserRecipeList.as_view(),
          name='user_recipes'),
]

recipes/urls.py
from django.urls import path

from . import views


app_name = 'recipes'
urlpatterns = [
     path('', views.RecipeList.as_view(), name='recipes_list'),
     path('recipe/<slug>', views.ViewRecipe.as_view(), name='recipe'),
     path('add_recipe/', views.CreateRecipe.as_view(), name='add_recipe'),
     path('edit_recipe/<pk>', views.UpdateRecipe.as_view(),
          name='edit_recipe'),
     path('delete_recipe/<pk>', views.DeleteRecipe.as_view(),
          name='delete_recipe'),
     path('edit_comment/<pk>', views.EditComment.as_view(),
          name='edit_comment'),
     path('delete_comment/<pk>', views.DeleteComment.as_view(),
          name='delete_comment'),
     path('submit_recipe/', views.SubmitRecipe.as_view(),
          name='submit_recipe'),
     path('edit_submitted/<pk>', views.EditSubmittedRecipe.as_view(),
          name='edit_submitted'),
     path('delete_submitted/<pk>', views.DeleteSubmittedRecipe.as_view(),
          name='delete_submitted'),
]

thechillibox/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('products/', include('products.urls')),
    path('management/', include('management.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('recipes/', include('recipes.urls')),
]


handler403 = "home.views.handle_403"
handler404 = "home.views.handle_404"
handler405 = "home.views.handle_405"
handler500 = "home.views.handle_500"

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from django_countries.fields import CountryField

from products.models import Product


class UserProfile(models.Model):
    """
    A user profile model for maintaining delivery information and order history
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=40, null=True, blank=True)
    last_name = models.CharField(max_length=80, null=True, blank=True)
    display_name = models.CharField(max_length=40, null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    street_address1 = models.CharField(max_length=80, null=True, blank=True)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    country = CountryField(blank_label='Country', null=True, blank=True)
    postcode = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        verbose_name_plural = "User Profiles"

    def __str__(self):
        return self.display_name

    def save(self, *args, **kwargs):
        """
        Override save to save display_name as username in case user hasn't
        added
        """
        if not self.display_name:
            self.display_name = self.user.username
        super(UserProfile, self).save(*args, **kwargs)


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """
    Create or update the user profile.
    """
    if created:
        UserProfile.objects.create(user=instance)
    # Existing users: just save the profile
    instance.userprofile.save()


class Reviews(models.Model):
    """
    User reviews for products
    """
    reviewer = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                 null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='reviews')
    content = models.TextField()
    rating = models.PositiveIntegerField()
    added_on = models.DateTimeField(auto_now_add=True)
    last_edited = models.DateField(auto_now=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.content

profiles/forms.py
from django import forms

from .models import UserProfile, Reviews


class ProfileForm(forms.ModelForm):
    """
    Profile form for user to add/edit details
    """
    class Meta:
        model = UserProfile
        exclude = ['user']


class DeleteAccountForm(forms.Form):
    """
    Simple form that provides a checkbox that signals deletion.
    """
    delete = forms.BooleanField(required=True)


class ReviewForm(forms.ModelForm):
    """
    Review form for user to edit review
    """
    class Meta:
        model = Reviews
        fields = ('content', 'rating',)
        widgets = {
            'content': forms.Textarea(attrs={'cols': 40, 'rows': 5}),
            'rating': forms.NumberInput(attrs={'min': 1, 'max': 5, 'step': 1})
        }
        labels = {
            'content': 'Your review:',
            'rating': 'Your rating (from 1 to 5):'
        }

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View, generic
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth.models import User
from django.contrib.auth import logout

from checkout.models import Order
from recipes.models import SubmittedRecipe

from .models import UserProfile, Reviews
from .forms import ProfileForm, DeleteAccountForm


class ProfileView(LoginRequiredMixin, View):
    """
    Profile view
    Generic view
    With LoginRequiredMixin as only registered user's have
    profiles, so redirects to login for users not logged in
    """
    def get(self, request):
        profile = get_object_or_404(UserProfile, user=request.user)
        orders = profile.orders.all().order_by('-date')
        template_name = 'profiles/profile.html'
        context = {
            'profile': profile,
            'orders': orders,
            }
        return render(request, template_name, context)


class UpdateProfile(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Update Profile view
    UpdateView - form_class included to exclude "user" field from form
    LoginRequiredMixin as only registered user's have profiles so redirects to
    login for users not logged in
    SuccessMessageMixin so success message displayed when successfully
    submitted
    """
    model = UserProfile
    form_class = ProfileForm
    template_name = 'profiles/profile_form.html'
    success_url = '/profiles/profile/'
    success_message = 'Your details were updated successfully.'

    def get_object(self):
        return self.request.user.userprofile


class DeleteAccount(LoginRequiredMixin, View):
    """
    Deletes the currently signed-in user
    LoginRequiredMixin as only registered user may need to delete account
    """
    def get(self, request, *args, **kwargs):
        """
        Get the confirm delete template with DeleteAccountForm
        """
        form = DeleteAccountForm()
        template_name = 'profiles/confirm_delete.html'
        context = {
            'form': form,
        }
        return render(request, template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Deletes user
        Redirects to index
        """
        template_name = 'profiles/confirm_delete.html'
        form = DeleteAccountForm(request.POST)
        if form.is_valid():
            user = request.user
            logout(request)
            user.delete()
            messages.success(request, 'You account was deleted.')
            return redirect('/')
        context = {
            'form': form,
        }
        return render(request, template_name, context)


class ReviewList(LoginRequiredMixin, generic.ListView):
    """
    Review list view
    Generic list view, paginated
    Queryset filtered to return reviews by user, ordered by most recent
    """
    model = Reviews
    template_name = 'profiles/review_list.html'
    paginate_by = 5

    def get_queryset(self):
        queryset = Reviews.objects.filter(reviewer=self.request.user.userprofile).order_by('-added_on')  # noqa
        return queryset


class EditReview(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Edit review view
    UpdateView - only two fields required so specified in view
    LoginRequiredMixin as only registered user's can edit reviews so redirects
    to login for users not logged in
    SuccessMessageMixin so success message displayed when successfully
    submitted
    """
    model = Reviews
    fields = ('content', 'rating',)
    template_name = 'profiles/review_form.html'
    success_url = '/profiles/review_list/'
    success_message = 'Your review was updated'


class DeleteReview(LoginRequiredMixin, DeleteView):
    """
    Delete review view
    DeleteView used
    LoginRequiredView as only registered user's and staff can delete reviews
    """
    model = Reviews
    template_name = 'profiles/delete_review.html'
    success_url = '/profiles/review_list/'


class OrderHistory(LoginRequiredMixin, View):
    """
    Order history view
    Generic view
    LoginRequiredView as only registered user's can view their order history
    from their profile
    Gets order using checkout success template
    """
    def get(self, request, order_number):
        order = get_object_or_404(Order, order_number=order_number)
        template_name = 'checkout/checkout_success.html'
        context = {
            'order': order,
        }
        return render(request, template_name, context)


class UserRecipeList(generic.ListView):
    """
    User recipe list
    Genergic list view, paginated
    Queryset filtered to return user's own submitted recipes order by date
    submitted on
    """
    model = SubmittedRecipe
    template_name = 'profiles/user_recipes.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = SubmittedRecipe.objects.filter(user=self.request.user).order_by('-submitted_on')  # noqa
        return queryset

profiles/templates/profiles/confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
Confirm Delete
{% endblock %}

{% block content %}

<div class="col-md-6 mx-auto">
    <!-- Confirm delete account -->
    <form method="POST">
        {% csrf_token %}
        <h1 class="headings headings-sm">Are you sure?</h1>
        <p>Deleting your account is <strong>not</strong> reversible.</p>
        <p>If you need to access your order history in future, you will need to contact support.</p>
        {{ form|crispy }}
        <button class="chilli-btn chilli-dngr" type="submit">Yes, delete</button>
    </form>
</div>

{% endblock %}

profiles/templates/profiles/delete_review.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
Confirm Delete
{% endblock %}

{% block content %}

<div class="col-md-6 mx-auto">
    <!-- Confirm delete -->
    <form method="POST">
        {% csrf_token %}
        <h1 class="headings headings-sm">Are you sure?</h1>
        <button class="chilli-btn chilli-dngr" type="submit">Yes, delete</button>
    </form>
</div>

{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'base.html' %}

{% block title %}
{{ profile }}
{% endblock %}

{% block content %}
<!-- User Profile Details -->
<section class="row">
    <div class="text-center">
        <h2 class="headings mb-2">Your Profile</h2>
        <div class="d-flex flex-row justify-content-center">
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'profiles:review_list' %}">Your Reviews</a>
            </div>
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'profiles:user_recipes' %}">Your Recipes</a>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-6">    
        <div class="col-sm-10 mx-auto">
            <h2 class="headings mb-2">Your Details</h2>
            <!-- Profile Options -->
            <div class="d-flex flex-row justify-content-between mb-3">
                <a class="chilli-btn" href="{% url 'profiles:edit_profile' %}">Edit Details</a>
                <a class="chilli-btn chilli-dngr" href="{% url 'profiles:delete_account' %}">Delete Account</a>
            </div>
            <!-- Detail table-->
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th>First Name: </th>
                        <td>{{ profile.first_name }} </td>
                    </tr>
                    <tr>
                        <th>Last Name: </th>
                        <td>{{ profile.last_name }} </td>
                    </tr>
                    <tr>
                        <th>Username: </th>
                        <td>{{ profile.user.username }} </td>
                    </tr>
                    <tr>
                        <th>Display Name: </th>
                        <td>{{ profile.display_name }} </td>
                    </tr>
                    <tr>
                        <th>Phone Number: </th>
                        <td>{{ profile.phone_number }} </td>
                    </tr>
                    <tr>
                        <th>Email: </th>
                        <td class="text-break">{{ profile.user.email }} </td>
                    </tr>
                </table>
            </div>
            <!-- Delivery details -->
            <h2 class="headings">Your Address</h2>
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th>Street Address: </th>
                        <td>{{ profile.street_address1 }} </td>
                    </tr>
                    {% if profile.street_address2 %}
                    <tr>
                        <th>Street Address 2:</th>
                        <td>{{ profile.street_address2 }} </td>
                    </tr>
                    {% endif %}
                    <tr>
                        <th>Town Or City: </th>
                        <td>{{ profile.town_or_city }} </td>
                    </tr>
                    <tr>
                        <th>County: </th>
                        <td>{{ profile.county }} </td>
                    </tr>
                    <tr>
                        <th>Country: </th>
                        <td>{{ profile.country }} </td>
                    </tr>
                    <tr>
                        <th>Postcode: </th>
                        <td>{{ profile.postcode }} </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <!-- User Order History -->
    <div class="col-12 col-md-6">
        <div class="col-sm-10 mx-auto">
            <h2 class="headings">Your Order History</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Order #</th>
                            <th>Date</th>
                            <th>Total</th>
                            <th>View</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                        <tr>
                            <td>{{ order.order_number|truncatechars:8 }}</td>
                            <td>{{ order.date|date:'d/m/y' }}</td>
                            <td>{{ order.grand_total }}</td>
                            <td>
                                <a class="chilli-btn" href="{% url 'profiles:order_history' order.order_number %}">
                                    View
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

{% endblock %}

profiles/templates/profiles/profile_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Edit Profile
{% endblock %}

{% block content %}
<div class="container-md">
    <div class="col-md-8 mx-auto">
        <!-- Form for editing profile details -->
        <h1 class="headings headings-sm text-center">Edit Your Details</h1>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ form|crispy}}
            <button class="chilli-btn" type="submit chilli-go">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

profiles/templates/profiles/review_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Edit Review
{% endblock %}

{% block content %}
<section class="container-md">
    <div class="col-md-8 mx-auto">
        <!-- Review form for editing -->
        <h1 class="headings headings-sm">Edit Review</h1>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ form|crispy}}
            <button class="chilli-btn chilli-go" type="submit">Submit</button>
        </form>
    </div>
</section>

{% endblock %}

profiles/templates/profiles/review_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Your Reviews
{% endblock title %}

{% block content %}
<section class="container-fluid">
    <div class="text-center">
        <!-- Navigation within profile -->
        <h2 class="headings mb-2">Your Reviews</h2>
        <div class="d-flex flex-row justify-content-center">
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'profiles:profile' %}">Your Profile</a>
            </div>
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'profiles:user_recipes' %}">Your Recipes</a>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="col-sm-10 mx-auto">
            <!-- List of user's reviews-->
            {% for review in reviews_list %}
            <div class="col-md-6 mx-auto">
                <h2 class="headings big">
                    Review for <a class="chilli-link" href="{% url 'products:product' review.product.slug %}">{{ review.product}}</a> <span class="small">on {{ review.added_on|date:'d/m/y' }}</span></h2>
                <p class="card p-2">{{ review }}</p>
                <p><strong>Rating: </strong>
                    {% if review.rating == 1 %}
                    <img width="33" height="80" class="rate-pics" src="{% static 'images/rate1.png' %}" alt="Rating">
                    {% elif review.rating == 2 %}
                    <img width="63" height="80" class="rate-pics" src="{% static 'images/rate2.png' %}" alt="Rating">
                    {% elif review.rating == 3 %}
                    <img width="93" height="80" class="rate-pics" src="{% static 'images/rate3.png' %}" alt="Rating">
                    {% elif review.rating == 4 %}
                    <img width="124" height="80" class="rate-pics" src="{% static 'images/rate4.png' %}" alt="Rating">
                    {% else %}
                    <img width="154" height="80" class="rate-pics" src="{% static 'images/rate5.png' %}" alt="Rating">
                    {% endif %}
                </p>
                <div class="d-flex flex-row justify-content-evenly">
                    <a class="chilli-btn chilli-go" href="{% url 'profiles:edit_review' review.pk %}">Edit Review</a>
                    <a class="chilli-btn chilli-dngr" href="{% url 'profiles:delete_review' review.pk %}">Delete Review</a>
                </div>
            </div>
            {% empty %}
            <p>You haven't written any reviews yet!</p>
            {% endfor %}
        </div>
    </div>
        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number" class="page-link">&laquo; PREV</a></li>
                {% endif %}
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number" class="page-link">NEXT &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
</section>
{% endblock content %}

profiles/templates/profiles/user_recipes.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Your Recipes
{% endblock title %}

{% block content %}
<section class="container-fluid">
    <div class="text-center">
        <!-- Navigation within profile -->
        <h2 class="headings mb-2">Your Recipes</h2>
        <div class="d-flex flex-row justify-content-center">
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'profiles:profile' %}">Your Profile</a>
            </div>
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'profiles:review_list' %}">Your Reviews</a>
            </div>
        </div>
    </div>
    <div class="col-12">
        <!-- Submit recipe button -->
        <div class="text-center my-3">
            <a class="chilli-btn" href="{% url 'recipes:submit_recipe' %}">Submit Recipe</a>
        </div>
        <!-- List of user's submitted recipes -->
        <div class="col-sm-10 mx-auto">
            {% for recipe in submittedrecipe_list %}
            <div class="col-md-6 mx-auto">
                <div class="recipe-card">
                    <h2 class="headings big">{{ recipe }}</h2>
                    <div>
                        <span class="small">Submitted on {{ recipe.submitted_on|date:'d/m/y' }}</span>
                    </div>
                    <div>
                        {{ recipe.ingredients|linebreaks }}
                    </div>
                    <div>
                        {{ recipe.directions|linebreaks }}
                    </div>
                    <div>
                        {{ recipe.notes|linebreaks }}
                    </div>
                </div>
                {% if recipe.published %}
                <p>
                    Your submitted recipe has been publish! If you make any changes to your submitted recipe they will not be reflected in the published version.
                </p>
                {% else %}
                <p>
                    Your recipe has been submitted. We will update you here if it is published.
                </p>
                {% endif %}
                {% if user.is_authenticated %}
                <div class="d-flex flex-row justify-content-evenly">
                    <a class="chilli-btn chilli-go" href="{% url 'recipes:edit_submitted' recipe.pk %}">Edit recipe</a>
                    <a class="chilli-btn chilli-dngr" href="{% url 'recipes:delete_submitted' recipe.pk %}">Delete recipe</a>
                </div>
                {% endif %}
            </div>
            {% empty %}
            <p>You haven't submitted any recipes yet!</p>
            {% endfor %}
        </div>
    </div>
    <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number" class="page-link">&laquo; PREV</a></li>
                {% endif %}
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number" class="page-link">NEXT &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
</section>
{% endblock content %}