cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.ViewCart.as_view(), name='view_cart'),
    path('add/<item_id>', views.add_to_cart, name='add_to_cart'),
    path('update/<item_id>', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>', views.remove_item, name='remove_item'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('privacy/', views.PrivacyPolicyView.as_view(), name='privacy'),
    path('faq/', views.FaqView.as_view(), name='faq')
]

products/urls.py
from django.urls import path

from . import views


app_name = 'products'
urlpatterns = [
    path('', views.LatestProducts.as_view(), name='latest'),
    path('category/<str:slug>', views.CategoryView.as_view(), name='category'),
    path('product/<slug>', views.ProductDetail.as_view(), name='product'),
    path('current_stock/', views.current_stock, name='current_stock'),
    path('search_results/', views.SearchResults.as_view(),
         name='search_results'),
]

profiles/urls.py
from django.urls import path

from . import views


app_name = 'profiles'
urlpatterns = [
     path('profile/', views.ProfileView.as_view(), name='profile'),
     path('edit_profile/', views.UpdateProfile.as_view(), name='edit_profile'),
     path('delete_account/', views.DeleteAccount.as_view(),
          name='delete_account'),
     path('order_history/<order_number>', views.OrderHistory.as_view(),
          name='order_history'),
     path('review_list/', views.ReviewList.as_view(), name='review_list'),
     path('edit_review/<pk>', views.EditReview.as_view(), name='edit_review'),
     path('delete_review/<pk>', views.DeleteReview.as_view(),
          name='delete_review'),
     path('user_recipes/', views.UserRecipeList.as_view(),
          name='user_recipes'),
]

recipes/urls.py
from django.urls import path

from . import views


app_name = 'recipes'
urlpatterns = [
     path('', views.RecipeList.as_view(), name='recipes_list'),
     path('recipe/<slug>', views.ViewRecipe.as_view(), name='recipe'),
     path('add_recipe/', views.CreateRecipe.as_view(), name='add_recipe'),
     path('edit_recipe/<pk>', views.UpdateRecipe.as_view(),
          name='edit_recipe'),
     path('delete_recipe/<pk>', views.DeleteRecipe.as_view(),
          name='delete_recipe'),
     path('edit_comment/<pk>', views.EditComment.as_view(),
          name='edit_comment'),
     path('delete_comment/<pk>', views.DeleteComment.as_view(),
          name='delete_comment'),
     path('submit_recipe/', views.SubmitRecipe.as_view(),
          name='submit_recipe'),
     path('edit_submitted/<pk>', views.EditSubmittedRecipe.as_view(),
          name='edit_submitted'),
     path('delete_submitted/<pk>', views.DeleteSubmittedRecipe.as_view(),
          name='delete_submitted'),
]

thechillibox/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('products/', include('products.urls')),
    path('management/', include('management.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('recipes/', include('recipes.urls')),
]


handler403 = "home.views.handle_403"
handler404 = "home.views.handle_404"
handler405 = "home.views.handle_405"
handler500 = "home.views.handle_500"

templates/includes/footer.html
<!-- Footer with short description of app, contact details and social links -->
<footer class="footer mt-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 text-center">
                <h2 class="footer-headings">Contact Us</h2>
                <p>
                    The Chillibox,<br>
                    Kill Village,<br>
                    Kildare.
                </p>
                <p>
                    Find out how to <a class="chilli-link-alt" href="{% url 'home:contact' %}">contact us here</a>.
                </p>
            </div>
            <div class="col-md-4">
                <!-- Begin Mailchimp Signup Form -->
                <link href="//cdn-images.mailchimp.com/embedcode/classic-071822.css" rel="stylesheet" type="text/css">
                <div id="mc_embed_signup">
                    <form
                        action="https://gmail.us18.list-manage.com/subscribe/post?u=a555a78c1c0e0713634b8751c&amp;id=1946d67f26&amp;f_id=007527e7f0"
                        method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate"
                        target="_blank" novalidate>
                        <div id="mc_embed_signup_scroll">
                            <h2>The Chillibox Newsletter</h2>
                            <div class="mc-field-group text-contain my-0">
                                <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="Email Address"
                                    required>
                            </div>
                            <div id="mce-responses">
                                <div class="response" id="mce-error-response" style="display:none"></div>
                                <div class="response" id="mce-success-response" style="display:none"></div>
                            </div>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"
                                    name="b_a555a78c1c0e0713634b8751c_1946d67f26" tabindex="-1" value=""></div>
                            <div class="optionalParent">
                                <div>
                                    <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe"
                                        class="chilli-btn chilli-go border-0">
                                    <p class="brandingLogo" hidden><a href="http://eepurl.com/ifwj6j"
                                            title="Mailchimp - email marketing made easy and fun"><img
                                                src="https://eep.io/mc-cdn-images/template_images/branding_logo_text_dark_dtp.svg"
                                                alt="Mailchimp newsletter"></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!--End mc_embed_signup-->
            </div>
            <div class="col-md-4 text-center">
                <h2 class="footer-headings">Social Media</h2>
                <p>
                    <a class="chilli-link-alt footer-socials" href="https://facebook.com" target="_blank" rel="noopener"
                        aria-label="Find us on Facebook (opens in new tab)"><i class="fa-brands fa-facebook"></i></a>
                    <a class="chilli-link-alt footer-socials" href="https://twitter.com" target="_blank" rel="noopener"
                        aria-label="Find us on Twitter (opens in new tab)"><i class="fa-brands fa-twitter"></i></a>
                </p>
            </div>
        </div>
        <div class="row text-center">
            <p>For educational purposes only.</p>
        </div>
    </div>
</footer>

<!-- Script for Mailchimp newsletter signup-->
<script src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'>
</script>
<script>
    (function ($) {
        window.fnames = new Array();
        window.ftypes = new Array();
        fnames[0] = 'EMAIL';
        ftypes[0] = 'email';
        fnames[1] = 'FNAME';
        ftypes[1] = 'text';
        fnames[2] = 'LNAME';
        ftypes[2] = 'text';
        fnames[3] = 'ADDRESS';
        ftypes[3] = 'address';
        fnames[4] = 'PHONE';
        ftypes[4] = 'phone';
        fnames[5] = 'BIRTHDAY';
        ftypes[5] = 'birthday';
    }(jQuery));
    var $mcj = jQuery.noConflict(true);
</script>

templates/includes/header.html
{% load static %}

<header>
    <nav id="navbar" class="navbar navbar-expand-lg">
        <div class="container-sm d-flex justify-content-between">
            <!-- Navbar logo-->
            <a class="navbar-brand" href="{% url 'home:index' %}" aria-label="Go to home page"><img width="90"
                    height="64" src="{% static 'images/chilli-logo-white.png' %}" alt="The Chillibox Logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <i class="fa-solid fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <!-- Search -->
                    <li class="nav-item m-2 px-2">
                        <form action="{% url 'products:search_results' %}" method="GET">
                            <input name="q" type="text" placeholder="Search...">
                            <button type="submit" class="chilli-link bg-light rounded" aria-label="Search">
                                <i class="fa-solid fa-magnifying-glass"></i>
                            </button>
                        </form>
                    </li>
                    <!-- Shop drop down-->
                    <li class="nav-item dropdown">
                        <a class="navbar-links dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Shop
                        </a>
                        <ul class="dropdown-menu drop-menu nav-drop-bg">
                            <li>
                                <a class="navbar-links" href="{% url 'products:latest' %}">Latest</a>
                            </li>
                            <li>
                                <a class="navbar-links" href="{% url 'products:category' slug='sauces' %}">Sauces</a>
                            </li>
                            <li>
                                <a class="navbar-links" href="{% url 'products:category' slug='seeds' %}">Seeds</a>
                            </li>
                            <li>
                                <a class="navbar-links"
                                    href="{% url 'products:category' slug='saucebox' %}">SauceBoxes</a>
                            </li>
                            <li>
                                <a class="navbar-links"
                                    href="{% url 'products:category' slug='seedbox' %}">SeedBoxes</a>
                            </li>
                        </ul>
                    </li>
                    <!-- Recipe page link -->
                    <li class="nav-item">
                        <a class="navbar-links" href="{% url 'recipes:recipes_list' %}">Recipes</a>
                    </li>
                    <!-- Help dropdown -->
                    <li class="nav-item dropdown">
                        <a class="navbar-links dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Help
                        </a>
                        <ul class="dropdown-menu drop-menu nav-drop-bg">
                            <li>
                                <a class="navbar-links navbar-drop-link" href="{% url 'home:faq' %}">FAQ</a>
                            </li>
                            <li>
                                <a class="navbar-links navbar-drop-link" href="{% url 'home:privacy' %}">Privacy
                                    Policy</a>
                            </li>
                            <li>
                                <a class="navbar-links navbar-drop-link" href="{% url 'home:contact' %}">Contact Us</a>
                            </li>
                        </ul>
                    </li>
                    <!-- Account drop down -->
                    <li class="nav-item dropdown">
                        <a class="navbar-links dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Account
                        </a>
                        <ul class="dropdown-menu drop-menu nav-drop-bg">
                            {% if user.is_authenticated %}
                            <!-- Staff link to management dashboard, users link to home -->
                            {% if user.is_staff %}
                            <li>
                                <a class="navbar-links navbar-drop-link"
                                    href="{% url 'management:dashboard' %}">Management</a>
                            </li>
                            {% endif %}
                            <li>
                                <a class="navbar-links navbar-drop-link" href="{% url 'profiles:profile' %}">My
                                    Profile</a>
                            </li>
                            <li>
                                <a class="navbar-links navbar-drop-link" href="{% url 'account_logout' %}">Logout</a>
                            </li>
                            {% else %}
                            <li>
                                <a class="navbar-links navbar-drop-link" href="{% url 'account_login' %}">Login</a>
                            </li>
                            <li>
                                <a class="navbar-links navbar-drop-link" href="{% url 'account_signup' %}">Register</a>
                            </li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- Cart -->
            <a class="navbar-links pb-0 mb-0" data-bs-toggle="offcanvas" href="#theCart" role="button" aria-label="Cart">
                <i class="fa-solid fa-cart-shopping big">
                {% if product_count > 0 %}<span class="small">{{ product_count }}</span>{% endif %}
                </i>
            </a>
        </div>
    </nav>
</header>