cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.ViewCart.as_view(), name='view_cart'),
    path('add/<item_id>', views.add_to_cart, name='add_to_cart'),
    path('update/<item_id>', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>', views.remove_item, name='remove_item'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
]

management/urls.py
from django.urls import path

from . import views


app_name = 'management'
urlpatterns = [
     path('', views.ProductDashboard.as_view(), name='dashboard'),
     path('add_variant/<slug>', views.AddVariant.as_view(),
          name='add_variant'),
     path('edit_variant/<pk>', views.EditVariant.as_view(),
          name='edit_variant'),
     path('delete_variant/<pk>', views.DeleteVariant.as_view(),
          name='delete_variant'),
     path('add_product/', views.AddProduct.as_view(), name='add_product'),
     path('edit_product/<pk>', views.EditProduct.as_view(),
          name='edit_product'),
     path('delete_product/<pk>', views.DeleteProduct.as_view(),
          name='delete_product'),
     path('user_reviews/', views.ReviewDashboard.as_view(),
          name='user_reviews'),
     path('approve_review/<pk>', views.approve_review, name='approve_review'),
     path('remove_review/<pk>', views.RemoveReview.as_view(),
          name='remove_review'),
     path('update_stock/<pk>', views.update_stock, name='update_stock'),
     path('recipes/', views.RecipeList.as_view(), name='recipes'),
     path('publish_recipe/<pk>', views.publish_recipe, name='publish_recipe'),
     path('recipe_comments/', views.CommentList.as_view(),
          name='recipe_comments'),
     path('approve_comment/<pk>', views.approve_comment,
          name='approve_comment'),
     path('user_recipes/', views.UserRecipeList.as_view(),
          name='user_recipes'),
     path('publish_submitted/<pk>', views.publish_submitted_recipe,
          name='publish_submitted'),
]

products/urls.py
from django.urls import path

from . import views


app_name = 'products'
urlpatterns = [
    path('', views.LatestProducts.as_view(), name='latest'),
    path('category/<str:slug>', views.CategoryView.as_view(), name='category'),
    path('product/<slug>', views.ProductDetail.as_view(), name='product'),
    path('current_stock/', views.current_stock, name='current_stock'),
    path('search_results/', views.SearchResults.as_view(),
         name='search_results'),
]

recipes/urls.py
from django.urls import path

from . import views


app_name = 'recipes'
urlpatterns = [
     path('', views.RecipeList.as_view(), name='recipes_list'),
     path('recipe/<slug>', views.ViewRecipe.as_view(), name='recipe'),
     path('add_recipe/', views.CreateRecipe.as_view(), name='add_recipe'),
     path('edit_recipe/<pk>', views.UpdateRecipe.as_view(),
          name='edit_recipe'),
     path('delete_recipe/<pk>', views.DeleteRecipe.as_view(),
          name='delete_recipe'),
     path('edit_comment/<pk>', views.EditComment.as_view(),
          name='edit_comment'),
     path('delete_comment/<pk>', views.DeleteComment.as_view(),
          name='delete_comment'),
     path('submit_recipe/', views.SubmitRecipe.as_view(),
          name='submit_recipe'),
     path('edit_submitted/<pk>', views.EditSubmittedRecipe.as_view(),
          name='edit_submitted'),
     path('delete_submitted/<pk>', views.DeleteSubmittedRecipe.as_view(),
          name='delete_submitted'),
]

thechillibox/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('products/', include('products.urls')),
    path('management/', include('management.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('recipes/', include('recipes.urls')),
]


handler403 = "home.views.handle_403"
handler404 = "home.views.handle_404"
handler405 = "home.views.handle_405"
handler500 = "home.views.handle_500"

management/forms.py
from django import forms
from products.models import Variant


class StockForm(forms.ModelForm):
    """
    ModelForm for current_stock so staff can update.
    """
    class Meta:
        """
        Only want current_stock field.
        """
        model = Variant
        fields = ['current_stock', ]

recipes/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    """
    Comment form for use on recipe page
    Specify text area
    """
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'cols': 40, 'rows': 5}),
        }

management/views.py
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View, generic
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from profiles.models import Reviews
from products.models import Category, Product, Variant
from recipes.models import Recipe, Comment, SubmittedRecipe

from .mixins import StaffRequiredMixin
from .forms import StockForm


class ProductDashboard(StaffRequiredMixin, View):
    """
    View for admin accessible management dashboard.
    """
    def get(self, request):
        products = Product.objects.all().order_by('category', 'subcategory')
        template_name = 'management/dashboard.html'
        context = {
            'products': products,
        }
        return render(request, template_name, context)


class AddVariant(StaffRequiredMixin, SuccessMessageMixin, CreateView):
    """ Add Variant View for management dashboard """
    model = Variant
    fields = ('size', 'price', 'current_stock',)
    template_name = 'management/dashboard_form.html'
    success_url = '/management/'
    success_message = '%(size)s was created'

    def form_valid(self, form):
        product = get_object_or_404(Product, slug=self.kwargs['slug'])
        form.instance.product = product
        return super(AddVariant, self).form_valid(form)


class EditVariant(StaffRequiredMixin, SuccessMessageMixin, UpdateView):
    """ Edit Variant View for management dashboard """
    model = Variant
    fields = '__all__'
    template_name = 'management/dashboard_form.html'
    success_url = '/management/'
    success_message = '%(size)s was updated'


class DeleteVariant(StaffRequiredMixin, DeleteView):
    """ Delete Variant View for management dashboard """
    model = Variant
    template_name = 'management/confirm_delete.html'
    success_url = '/management/'


class AddProduct(StaffRequiredMixin, SuccessMessageMixin, CreateView):
    """ Add Product View for management dashboard """
    model = Product
    fields = '__all__'
    template_name = 'management/dashboard_form.html'
    success_url = '/management/'
    success_message = '%(name)s was created'


class EditProduct(StaffRequiredMixin, SuccessMessageMixin, UpdateView):
    """ Edit Product View for management dashboard """
    model = Product
    fields = '__all__'
    template_name = 'management/dashboard_form.html'
    success_url = '/management/'
    success_message = '%(name)s was updated'


class DeleteProduct(StaffRequiredMixin, DeleteView):
    """ Delete Product View for management dashboard """
    model = Product
    template_name = 'management/confirm_delete.html'
    success_url = '/management/'


class ReviewDashboard(StaffRequiredMixin, View):
    """
    View for admin accessible review dashboard.
    """
    def get(self, request):
        reviews = Reviews.objects.all().order_by('-added_on')
        template_name = 'management/user_reviews.html'
        context = {
            'reviews': reviews,
        }
        return render(request, template_name, context)


class RemoveReview(StaffRequiredMixin, DeleteView):
    """ Remove Review view for management dashboard """
    model = Reviews
    template_name = 'management/confirm_delete.html'
    success_url = '/management/user_reviews'


def approve_review(request, pk):
    """ Approve review function for management dashboard """
    if request.user.is_staff:
        review = get_object_or_404(Reviews, pk=pk)
        review.approved = True
        review.save()
        return redirect('management:user_reviews')
    else:
        return redirect('account_login')


def update_stock(request, pk):
    """ Update stock function for management dashboard """
    if request.user.is_staff:
        variant = Variant.objects.get(pk=pk)
        form = StockForm(request.POST or None, instance=variant)
        if form.is_valid():
            form.save()
            messages.success(request, f'{variant.size} stock updated.')
            return HttpResponse(status=204)
        else:
            form = StockForm(request.POST or None, instance=variant)
        context = {
            'variant': variant,
            'form': form,
        }
        return render(request, 'management/update_stock.html', context)
    else:
        return redirect('account_login')


class RecipeList(StaffRequiredMixin, generic.ListView):
    """ Recipe list view for management dashboard """
    model = Recipe
    template_name = 'management/recipes.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = Recipe.objects.order_by('-published', '-created')
        return queryset


def publish_recipe(request, pk):
    """ Publish recipe function for management dashboard """
    if request.user.is_staff:
        recipe = get_object_or_404(Recipe, pk=pk)
        recipe.published = True
        recipe.save()
        return redirect('management:recipes')
    else:
        return redirect('account_login')


class CommentList(StaffRequiredMixin, generic.ListView):
    """ Comment list view for management dashboard """
    model = Comment
    template_name = 'management/recipe_comments.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = Comment.objects.order_by('-approved')
        return queryset


def approve_comment(request, pk):
    """ Approve comment function for management dashboard """
    if request.user.is_staff:
        comment = get_object_or_404(Comment, pk=pk)
        comment.approved = True
        comment.save()
        return redirect('management:recipe_comments')
    else:
        return redirect('account_login')


class UserRecipeList(StaffRequiredMixin, generic.ListView):
    """ Submitted recipe list for management dashboard """
    model = SubmittedRecipe
    template_name = 'management/user_recipes.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = SubmittedRecipe.objects.order_by('-submitted_on')
        return queryset


def publish_submitted_recipe(request, pk):
    """ Publist submitted recipe function for management dashboard """
    if request.user.is_staff:
        recipe = get_object_or_404(SubmittedRecipe, pk=pk)
        recipe.published = True
        recipe.save()
        return redirect('management:user_recipes')
    else:
        return redirect('account_login')

recipes/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View, generic
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from management.mixins import StaffRequiredMixin
from .models import Recipe, Comment, SubmittedRecipe
from .forms import CommentForm


class RecipeList(generic.ListView):
    """
    Recipe list view
    Generic list view, paginated
    Queryset filter returns published recipes by date created
    """
    model = Recipe
    template_name = 'recipes/recipes.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = Recipe.objects.filter(published=True).order_by('-created')
        return queryset


class ViewRecipe(View):
    """
    Recipe view
    Generic view, using CommentForm from forms.py
    """
    def get(self, request, slug):
        recipe = get_object_or_404(Recipe, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('-added_on')
        template_name = 'recipes/recipe_detail.html'
        context = {
            'recipe': recipe,
            'comments': comments,
            'commented': False,
            'form': CommentForm(),
        }
        return render(request, template_name, context)

    def post(self, request, slug, *args, **kwargs):
        recipe = get_object_or_404(Recipe, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('-added_on')
        template_name = 'recipes/recipe_detail.html'
        form = CommentForm(data=request.POST)

        if form.is_valid():
            if request.user.is_authenticated:
                form.instance.user = request.user
                comment = form.save(commit=False)
                comment.recipe = recipe
                comment.save()
            else:
                comment = form.save(commit=False)
                comment.recipe = recipe
                comment.save()
        else:
            form = CommentForm()

        context = {
            'recipe': recipe,
            'comments': comments,
            'form': form,
            'commented': True,
        }
        return render(request, template_name, context)


class CreateRecipe(StaffRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Create Recipe view
    CreateView using Recipe model, specify fields
    StaffRequiredMixin as user must be registered and staff, otherwise
    redirects user
    SuccessMessageMixin to display success message when form submitted
    """
    model = Recipe
    fields = ('title', 'image', 'intro', 'excerpt', 'ingredients',
              'directions', 'outro',)
    template_name = 'recipes/recipe_form.html'
    success_url = '/management/recipes/'
    success_message = 'Your recipe was created.'


class UpdateRecipe(StaffRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Update recipe view
    UpdateView using Recipe model
    StaffRequiredMixin as user must be registered and staff, otherwise
    redirects user
    SuccessMessageMixin to display success message when form submitted
    """
    model = Recipe
    fields = ('title', 'image', 'intro', 'excerpt', 'ingredients',
              'directions', 'outro',)
    template_name = 'recipes/recipe_form.html'
    success_url = '/management/recipes/'
    success_message = 'Your recipe was updated.'


class DeleteRecipe(StaffRequiredMixin, DeleteView):
    """
    Delete recipe view
    DeleteView using Recipe model
    StaffRequiredMixin as user must be registered and staff, otherwise
    redirects user
    """
    model = Recipe
    template_name = 'management/confirm_delete.html'
    success_url = '/management/recipes/'


class EditComment(LoginRequiredMixin, UpdateView):
    """
    Edit comment view
    UpdateView - doesn't use CommentForm in forms.py, uses Comment model
    LoginRequiredMixin as only registered users can edit their comments
    """
    model = Comment
    fields = ('content',)
    template_name = 'recipes/comment_form.html'
    success_url = '/recipes/'


class DeleteComment(LoginRequiredMixin, DeleteView):
    """
    Delete comment view
    DeleteView using Comment model
    LoginRequiredMixin as only registered users and staff can delete comments
    """
    model = Comment
    template_name = 'management/confirm_delete.html'
    success_url = '/recipes/'


class SubmitRecipe(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Submit recipe view
    CreateView using SubmittedRecipe view
    LoginRequiredMixin as only registered users can submit recipes
    SuccessMessageMixin to display success message when user submits recipe
    """
    model = SubmittedRecipe
    fields = ('recipe_title', 'ingredients', 'directions', 'notes',)
    template_name = 'recipes/recipe_form.html'
    success_url = '/profiles/user_recipes/'
    success_message = 'Your recipe has been submitted.'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(SubmitRecipe, self).form_valid(form)


class EditSubmittedRecipe(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Edit submitted recipe view
    UpdateView using SubmittedRecipe model
    LoginRequiredMixin as only registered users can submit and edit recipes
    SuccessMessageMixin to display success message when user edits recipe
    """
    model = SubmittedRecipe
    fields = ('recipe_title', 'ingredients', 'directions', 'notes',)
    template_name = 'recipes/recipe_form.html'
    success_url = '/profiles/user_recipes/'
    success_message = 'Your recipe has been edited.'


class DeleteSubmittedRecipe(LoginRequiredMixin, DeleteView):
    """
    Delete submitted recipe view
    DeleteView using SubmittedRecipe
    LoginRequiredMixin as only registered users and staff can delete submitted
    recipes
    """
    model = SubmittedRecipe
    template_name = 'management/confirm_delete.html'
    success_url = '/profiles/user_recipes/'

management/templates/management/confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
Confirm Delete
{% endblock %}

{% block content %}

<!-- Simple confirm delete template -->
<div class="col-md-6 mx-auto">
    <form method="POST">
        {% csrf_token %}
        <h1 class="headings headings-sm">Are you sure?</h1>
        <button class="chilli-btn chilli-dngr" type="submit">Yes, delete</button>
    </form>
</div>

{% endblock %}

management/templates/management/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<section class="row">
    <!-- Management landing template - products -->
    <div class="text-center">
        <h2 class="headings mb-2">Products</h2>
        <div class="d-flex flex-row justify-content-center">
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'management:user_reviews' %}">Reviews</a>
            </div>
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'management:recipes' %}">Recipes</a>
            </div>
        </div>
    </div>
    <div class="text-center my-3">
        <div>
            <a class="chilli-btn" href="{% url 'management:add_product' %}">Add New Product</a>
        </div>
    </div>
    <small class="text-center warning-text">This page is best viewed on larger screens.</small>
    <!-- Group added products by category -->
    {% regroup products by category as products_by_category %}
    {% for category in products_by_category %}
    <div class="col-12 col-lg-6">
        <!-- Category heading -->
        <div class="d-flex flex-row justify-content-between align-items-center">
            <h2 class="headings">{{ category.grouper}}</h2>
            <span><strong>{{ category.list|length }}</strong> in {{ category.grouper }}</span>
        </div>
        {% regroup category.list by subcategory as subcategory_list %}
            {% for subcategory in subcategory_list %}
            <div class="d-flex flex-wor justify-content-between align-items-center">
                <h3 class="headings headings-sm">{{ subcategory.grouper }} {{ category.grouper }}</h3>
                <span><strong>{{ subcategory.list|length }}</strong> in {{ subcategory.grouper }}</span>
            </div>
            {% for product in subcategory.list %}
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr class="table-secondary">
                                <th>Name</th>
                                <th class="sm-prod-table">Thumbnail</th>
                                <th>Edit</th>
                                <th>Delete</th>
                                <th colspan="2">Add Variant</th>
                            </tr>
                        </thead>
                        <!-- Product details -->
                        <tbody>
                            <tr>
                                <td class="align-middle"><a class="chilli-link" href="{% url 'products:product' product.slug %}">
                                    {{ product.name }}</a></td>
                                <td class="align-middle sm-prod-table">{% if product.thumbnail %}Yes{% else %}No{% endif %}</td>
                                <td class="align-middle">
                                    <a class="chilli-btn" href="{% url 'management:edit_product' product.id %}">Edit</a>
                                </td>
                                <td class="align-middle">
                                    <a class="chilli-btn chilli-dngr"
                                        href="{% url 'management:delete_product' product.id %}">Delete</a>
                                </td>
                                <td class="align-middle">
                                    <a class="chilli-btn" href="{% url 'management:add_variant' product.slug %}">Add</a>
                                </td>
                                <td class="align-middle">
                                    <button class="chilli-btn" data-bs-toggle="collapse" data-bs-target="#collapse-{{ product.id }}"
                                        aria-expanded="false" aria-controls="collapse-{{ product.id }}">
                                        Variants
                                        <i class="fa-solid fa-caret-down"></i>
                                    </button>                            
                                </td>
                            </tr>
                            <tr>
                                <td colspan="6">
                                    <table class="table collapse" id="collapse-{{ product.id }}">
                                        <thead>
                                            <tr>
                                                <th>Size</th>
                                                <th class="sm-prod-table">Price</th>
                                                <th>Stock</th>
                                                <th>Update Stock</th>
                                                <th>Edit</th>
                                                <th>Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <!-- Product variants -->
                                            {% for variant in product.variants.all %}
                                            <tr>
                                                <td>{{ variant.size }}</td>
                                                <td class="sm-prod-table">{{ variant.price }}</td>
                                                <td>{{ variant.current_stock }}</td>
                                                <td><button class="chilli-btn" data-hx-get="{% url 'management:update_stock' variant.pk %}"
                                                        data-hx-target="#dialog" aria-label="Update {{ variant }} stock">Update</button></td>
                                                <td>
                                                    <a class="chilli-btn" href="{% url 'management:edit_variant' variant.id %}">Edit</a>
                                                </td>
                                                <td>
                                                    <a class="chilli-btn chilli-dngr"
                                                        href="{% url 'management:delete_variant' variant.id %}">Delete</a>
                                                </td>
                                            </tr>
                                            {% empty %}
                                            <tr>
                                                <td colspan="6">No variants added</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                {% endfor %}
        {% endfor %}
    </div>
    {% endfor %}
</section>

{% endblock %}
<!-- Script for modal for stock update -->
{% block additional_script %}
<script src="{% static 'js/modal.js' %}"></script>
{% endblock %}

management/templates/management/recipes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Recipes
{% endblock %}

{% block content %}
<!-- Manage recipes -->
<section class="row">
    <div class="text-center">
        <h2 class="headings mb-2">Recipes</h2>
        <div class="d-flex flex-row justify-content-center">
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'management:user_reviews' %}">Reviews</a>
            </div>
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'management:dashboard' %}">Products</a>
            </div>
        </div>
        <div class="d-flex flex-row justify-content-center">
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'management:user_recipes' %}">Submitted Recipes</a>
            </div>
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'management:recipe_comments' %}">Recipe Comments</a>
            </div>
        </div>
    </div>
    <div class="text-center my-3">
        <!-- Add recipe -->
        <div>
            <a class="chilli-btn" href="{% url 'recipes:add_recipe' %}">Add Recipe</a>
        </div>
    </div>
    <div class="col-12">
        <div class="col-10 mx-auto">
            <!-- List of created recipes -->
            {% for recipe in recipe_list %}
            <div class="col-lg-8 my-4 mx-auto">
                <h2 class="headings big"><a class="chilli-link" href="{% url 'recipes:recipe' recipe.slug %}">{{ recipe }} &raquo;</a></h2>
                <div>
                    <span class="small">Added on {{ recipe.created|date:'d/m/y' }}</span>
                    <p class="p-2">{{ recipe.excerpt }}</p>
                </div>
                <div class="row d-flex flex-row justify-content-between">
                    <div class="col-12 col-lg-6">
                        {% if recipe.published %}
                        <div>
                            <span><strong>Published</strong>: </span>
                            <a class="chilli-link" href="{% url 'recipes:recipe' recipe.slug %}">{{ recipe }}</a>
                        </div>
                        {% else %}
                        <!-- Publish recipe -->
                        <form action="{% url 'management:publish_recipe' recipe.pk %}" method="POST">
                            {% csrf_token %}
                            <input type="checkbox">
                            <button type="submit" class="chilli-btn chilli-go">Publish</button>
                        </form>
                        {% endif %}
                    </div>
                    <!-- Edit or delete recipe -->
                    <div class="col-12 col-lg-6">
                        <a class="chilli-btn chilli-go" href="{% url 'recipes:edit_recipe' recipe.pk %}">Edit recipe</a>
                        <a class="chilli-btn chilli-dngr" href="{% url 'recipes:delete_recipe' recipe.pk %}">Delete recipe</a>
                    </div>
                </div>
            </div>
            <hr>
            {% empty %}
            <p>There aren't any recipes yet!</p>
            {% endfor %}
        </div>
    </div>
        {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number" class="page-link">&laquo; PREV</a></li>
                {% endif %}
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number" class="page-link">NEXT &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
</section>
{% endblock %}

management/templates/management/user_reviews.html
{% extends 'base.html' %}

{% block title %}
User Reviews
{% endblock %}

{% block content %}
<!-- Manage user reviews -->
<section class="col">
    <div class="text-center">
        <h2 class="headings mb-2">User Reviews</h2>
        <div class="d-flex flex-row justify-content-center">
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'management:dashboard' %}">Products</a>
            </div>
            <div class="border border-2 p-1">
                <a class="chilli-link" href="{% url 'management:recipes' %}">Recipes</a>
            </div>
        </div>
    </div>
    <div>
        <!-- Manage user reviews -->
        {% for review in reviews %}
        <div class="col-sm-8 mx-auto my-3">
            <div class="row">
                <div class="col-sm-4">
                    <p><strong>
                        {% if review.reviewer is not None %}
                            {{ review.reviewer }}
                        {% else %}
                            Anonymous
                        {% endif %}
                    </strong></p>
                    <p>Added on {{ review.added_on|date:'d/m/y' }}</p>
                    <p>For: <a class="chilli-link" href="{% url 'products:product' review.product.slug %}">{{ review.product }}</a></p>
                </div>
                <div class="card col-sm-8">
                    {{ review.content }}
                </div>
                <div>
                    <p><strong>Rating: </strong>{{ review.rating }}</p>
                </div>
            </div>
            <div class="d-flex flex-row justify-content-between my-3 mx-sm-5">
                <!-- Remove the review from the site -->
                <a class="chilli-btn chilli-dngr" href="{% url 'management:remove_review' review.pk %}">Delete Review</a>
                {% if review.approved %}
                <span><strong>Published</strong></span>
                {% else %}
                <!-- Approve the review -->
                <form action="{% url 'management:approve_review' review.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="checkbox" aria-label="Approve review">
                    <button type="submit" class="chilli-btn chilli-go">Approve</button>
                </form>
                {% endif %}
            </div>
        </div>
        <hr>
        {% endfor %}
    </div>
</section>
{% endblock %}