cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.ViewCart.as_view(), name='view_cart'),
    path('add/<item_id>', views.add_to_cart, name='add_to_cart'),
    path('update/<item_id>', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>', views.remove_item, name='remove_item'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('privacy/', views.PrivacyPolicyView.as_view(), name='privacy'),
    path('faq/', views.FaqView.as_view(), name='faq')
]

management/urls.py
from django.urls import path

from . import views


app_name = 'management'
urlpatterns = [
     path('', views.ProductDashboard.as_view(), name='dashboard'),
     path('add_variant/<slug>', views.AddVariant.as_view(),
          name='add_variant'),
     path('edit_variant/<pk>', views.EditVariant.as_view(),
          name='edit_variant'),
     path('delete_variant/<pk>', views.DeleteVariant.as_view(),
          name='delete_variant'),
     path('add_product/', views.AddProduct.as_view(), name='add_product'),
     path('edit_product/<pk>', views.EditProduct.as_view(),
          name='edit_product'),
     path('delete_product/<pk>', views.DeleteProduct.as_view(),
          name='delete_product'),
     path('user_reviews/', views.ReviewDashboard.as_view(),
          name='user_reviews'),
     path('approve_review/<pk>', views.approve_review, name='approve_review'),
     path('remove_review/<pk>', views.RemoveReview.as_view(),
          name='remove_review'),
     path('update_stock/<pk>', views.update_stock, name='update_stock'),
     path('recipes/', views.RecipeList.as_view(), name='recipes'),
     path('publish_recipe/<pk>', views.publish_recipe, name='publish_recipe'),
     path('recipe_comments/', views.CommentList.as_view(),
          name='recipe_comments'),
     path('approve_comment/<pk>', views.approve_comment,
          name='approve_comment'),
     path('user_recipes/', views.UserRecipeList.as_view(),
          name='user_recipes'),
     path('publish_submitted/<pk>', views.publish_submitted_recipe,
          name='publish_submitted'),
]

products/urls.py
from django.urls import path

from . import views


app_name = 'products'
urlpatterns = [
    path('', views.LatestProducts.as_view(), name='latest'),
    path('category/<str:slug>', views.CategoryView.as_view(), name='category'),
    path('product/<slug>', views.ProductDetail.as_view(), name='product'),
    path('current_stock/', views.current_stock, name='current_stock'),
    path('search_results/', views.SearchResults.as_view(),
         name='search_results'),
]

profiles/urls.py
from django.urls import path

from . import views


app_name = 'profiles'
urlpatterns = [
     path('profile/', views.ProfileView.as_view(), name='profile'),
     path('edit_profile/', views.UpdateProfile.as_view(), name='edit_profile'),
     path('delete_account/', views.DeleteAccount.as_view(),
          name='delete_account'),
     path('order_history/<order_number>', views.OrderHistory.as_view(),
          name='order_history'),
     path('review_list/', views.ReviewList.as_view(), name='review_list'),
     path('edit_review/<pk>', views.EditReview.as_view(), name='edit_review'),
     path('delete_review/<pk>', views.DeleteReview.as_view(),
          name='delete_review'),
     path('user_recipes/', views.UserRecipeList.as_view(),
          name='user_recipes'),
]

thechillibox/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('products/', include('products.urls')),
    path('management/', include('management.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('recipes/', include('recipes.urls')),
]


handler403 = "home.views.handle_403"
handler404 = "home.views.handle_404"
handler405 = "home.views.handle_405"
handler500 = "home.views.handle_500"

products/models.py
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db.models import Sum

from django.db import models


SUBCATEGORIES = (('Mild', 'Mild'), ('Medium', 'Medium'), ('Hot', 'Hot'),
                 ('Mega Hot', 'Mega Hot'))


class Category(models.Model):
    """
    Category model.
    Order by name.
    String representation returns name.
    """
    name = models.CharField(max_length=255)
    slug = models.SlugField()

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    Product model.
    With method to create a thumbnail from uploaded image.
    In_stock boolean updates on save according to current_stock.
    String representation returns name.
    """
    category = models.ForeignKey(Category, on_delete=models.SET_NULL,
                                 null=True, blank=True, related_name='product')
    subcategory = models.CharField(max_length=8, choices=SUBCATEGORIES,
                                   blank=True)
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.TextField(null=True, blank=True,
                                   help_text='Include a description for the \
                                   product\'s page.')
    excerpt = models.TextField(null=True, blank=True, help_text='Include a \
                               brief summary of the product.')
    ingredients = models.CharField(max_length=140, null=True, blank=True,
                                   help_text='For sauces, please include the \
                                   ingredients.')
    growth_time = models.CharField(max_length=140, null=True, blank=True,
                                   help_text='For seeds, please include the \
                                   growth time to maturity.')
    heat_level = models.CharField(max_length=140, null=True, blank=True,
                                  help_text='In scovilles or more generally \
                                  (eg \'hot\') where appropriate.')
    box_contents = models.ManyToManyField('self', blank=True, help_text='Add \
                                          products for seed and sauce boxes.')
    image = models.ImageField(upload_to='uploads/', null=True, blank=True)
    thumbnail = models.ImageField(upload_to='uploads/', null=True, blank=True,
                                  help_text='If not added, will be \
                                  auto-generated from image.')
    added_on = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('name',)
        get_latest_by = ('added_on',)

    def __str__(self):
        return self.name

    def check_stock(self, *args, **kwargs):
        in_stock = False
        for variant in self.variants.all():
            if variant.in_stock:
                in_stock = True
        return in_stock

    def make_thumbnail(self, image):
        """
        Create thumbnail from uploaded image
        https://gist.github.com/valberg/2429288
        """
        if not self.image:
            return
        size = 160, 160
        img = Image.open(BytesIO(image.read()))
        img.thumbnail(size)

        temp_thumb = BytesIO()
        img.save(temp_thumb, 'PNG')
        temp_thumb.seek(0)

        thumbnail = SimpleUploadedFile(image.name, temp_thumb.read())

        return thumbnail

    def save(self, *args, **kwargs):
        """
        Override save to create thumbnail if image present but no thumbnail
        """
        super(Product, self).save(*args, **kwargs)
        if self.image:
            if not self.thumbnail:
                self.thumbnail = self.make_thumbnail(self.image)
                super(Product, self).save(*args, **kwargs)


class Variant(models.Model):
    """
    ProductVariant model. To manage options for sizes and prices.
    String representation returns variant size.
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='variants')
    size = models.CharField(max_length=80)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    current_stock = models.PositiveIntegerField(default=0,
                                                help_text='Default is 0.')
    in_stock = models.BooleanField(default=False,
                                   help_text='Updates when current stock \
                                   updated.')

    class Meta:
        verbose_name_plural = 'Variants'

    def __str__(self):
        return self.size

    @property
    def fulfillable_qty(self):
        """
        Fulfillabel quantity of product depending on current stock - held stock
        """
        qty_held = self.held_stock.aggregate(Sum('qty'))
        if qty_held['qty__sum'] is not None:
            return self.current_stock - int(qty_held['qty__sum'])
        else:
            return self.current_stock

    def save(self, *args, **kwargs):
        """
        Override save to set stock boolean depending on current stock
        """
        if self.current_stock < 1:
            self.in_stock = False
        elif self.current_stock >= 1:
            self.in_stock = True
        super(Variant, self).save(*args, **kwargs)

products/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView
from django.db.models import Q, Avg
from django.db.models.functions import Round

from profiles.forms import ReviewForm
from profiles.models import Reviews

from .models import Category, Variant, Product


class LatestProducts(View):
    """
    Latest product view
    Generic view
    """
    def get(self, request):
        seedcat = Product.objects.filter(category__name='Seeds').order_by('-added_on')[0:4]  # noqa
        saucecat = Product.objects.filter(category__name='Sauces').order_by('-added_on')[0:4]  # noqa
        seedboxcat = Product.objects.filter(category__name='Seedboxes').order_by('-added_on')[0:4]  # noqa
        sauceboxcat = Product.objects.filter(category__name='Sauceboxes').order_by('-added_on')[0:4]  # noqa
        template_name = 'products/latest_products.html'
        context = {
            'seedcat': seedcat,
            'saucecat': saucecat,
            'seedboxcat': seedboxcat,
            'sauceboxcat': sauceboxcat,
        }
        return render(request, template_name, context)


class CategoryView(View):
    """
    Category view
    Generic view
    """
    def get(self, request, slug, *args, **kwargs):
        """
        Filterkey in get to filter queryset
        """
        category = get_object_or_404(Category, slug=slug)
        products_list = Product.objects.filter(category__slug=slug).all()
        template_name = 'products/category.html'
        filterkey = self.request.GET.get('filter_subcat')
        if filterkey is None or filterkey == 'default':
            products = products_list
        else:
            products = products_list.filter(subcategory=filterkey.title())

        context = {
            'category': category,
            'products': products,
            'current_filterkey': filterkey,
        }
        return render(request, template_name, context)


class ProductDetail(View):
    """
    Product detail view
    Generic view
    Using ReviewForm from profiles app for review on product page
    Reviews filter returns approved reviews for current product
    Avg_rating is rounded average of those reviews
    """
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        reviews = product.reviews.filter(approved=True).order_by('-added_on')
        avg_rating = reviews.aggregate(rounded=Round(Avg('rating')))
        template_name = 'products/product_detail.html'
        context = {
            'product': product,
            'reviews': reviews,
            'avg_rating': avg_rating,
            'reviewed': False,
            'review_form': ReviewForm(),
        }
        return render(request, template_name, context)

    def post(self, request, slug, *args, **kwargs):
        product = get_object_or_404(Product, slug=slug)
        reviews = product.reviews.filter(approved=True).order_by('-added_on')
        avg_rating = reviews.aggregate(rounded=Round(Avg('rating')))
        template_name = 'products/product_detail.html'

        review_form = ReviewForm(data=request.POST)

        if review_form.is_valid():
            if request.user.is_authenticated:
                review_form.instance.reviewer = request.user.userprofile
                review = review_form.save(commit=False)
                review.product = product
                review.save()
            else:
                review = review_form.save(commit=False)
                review.product = product
                review.save()
        else:
            review_form = ReviewForm()

        context = {
            'product': product,
            'reviews': reviews,
            'avg_rating': avg_rating,
            'reviewed': True,
            'review_form': review_form,
        }

        return render(request, template_name, context)


class SearchResults(ListView):
    """
    Search results view
    Generic list view using Product model
    Using Q to query by name or description
    """
    model = Product
    template_name = 'products/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        product_list = Product.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )
        return product_list

    def get_context_data(self, **kwargs):
        context = super(SearchResults, self).get_context_data(**kwargs)
        context['search_term'] = self.request.GET.get('q')
        return context


def current_stock(request):
    """
    Current stock function
    Returns current stock when variant selected on product detail page
    """
    variant_id = request.GET.get('product_variant')
    if variant_id == 'default':
        return HttpResponse('')
    else:
        variant = Variant.objects.get(id=variant_id)
        current_stock = variant.fulfillable_qty
        return HttpResponse(current_stock)

products/templates/products/category.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ category }}
{% endblock %}

{% block content %}
<section class="container-md">
    <div>
        <!-- Category heading with add button for staff -->
        <div class="row d-flex flex-row align-items-center justify-content-between mb-3">
            <h2 class="headings col-6 col-sm-4">{{ category }}</h2>
            {% if user.is_staff %}
            <div class="col-6 col-sm-4">
                <a class="chilli-btn" href="{% url 'management:add_product' %}">Add Product</a>
            </div>
            {% endif %}
            <form class="col-12 col-sm-4" action="{% url 'products:category' category.slug %}" method="GET">
                <select id="filter_subcat" name="filter_subcat" class="border rounded-0">
                    <option value="default" {% if current_filterkey == "None" %}selected{% endif %}>All {{ category }}</option>
                    <option value="mild" {% if current_filterkey == "mild" %}selected{% endif %}>Mild</option>
                    <option value="medium" {% if current_filterkey == "medium" %}selected{% endif %}>Medium</option>
                    <option value="hot" {% if current_filterkey == "hot" %}selected{% endif %}>Hot</option>
                    <option value="mega hot" {% if current_filterkey == "mega hot" %}selected{% endif %}>Mega Hot</option>
                </select>
                <button class="chilli-btn px-1 py-0 rounded-1">Go</button>
            </form>
        </div>
    </div>
    <!-- Products-->
    <div class="row d-flex justify-content-evenly">
        {% for product in products %}
        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3 text-center">
            <div class="h-100 border-0 chilli-card text-center mx-auto">
                <div>
                    <h2 class="headings headings-sm">{{ product }}</h2>
                </div>
                <div class="my-3">
                    {% if product.thumbnail %}
                        <img width="160" height="160" class="pics thumbs" src="{{ product.thumbnail.url }}" alt="{{ product }}">
                    {% else %}
                        <img width="300" height="300" class="pics thumbs" src="{% static 'images/placeholder.png' %}" alt="No image available for {{ product }}">
                    {% endif %}
                </div>
                <div>
                    <div class="row">
                        <div class="col">
                            {% if product.excerpt %}
                            <p class="excerpt">{{ product.excerpt }}</p>
                            {% endif %}
                            {% if product.check_stock %}
                            <p>In stock.</p>
                            {% else %}
                            <p>Out of stock.</p>
                            {% endif %}
                            <a class="chilli-link" href="{% url 'products:product' product.slug %}">View
                                {{ product }}</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Staff options -->
            {% if user.is_staff %}
            <div class="my-3">
                <a class="chilli-btn" href="{% url 'management:edit_product' product.pk %}">Edit Product</a>
                <a class="chilli-btn chilli-dngr" href="{% url 'management:delete_product' product.pk %}">Delete
                    Product</a>
            </div>
            {% endif %}
        </div>
        {% if forloop.counter|divisibleby:1 %}
        <div class="col-12 d-sm-none my-5">
            <hr>
        </div>
        {% endif %}
        {% if forloop.counter|divisibleby:2 %}
        <div class="col-12 d-none d-sm-block d-md-block d-lg-none my-5">
            <hr>
        </div>
        {% endif %}
        {% if forloop.counter|divisibleby:3 %}
        <div class="col-12 d-none d-lg-block d-xl-none my-5">
            <hr>
        </div>
        {% endif %}
        {% if forloop.counter|divisibleby:4 %}
        <div class="col-12 d-none d-xl-block my-5">
            <hr>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</section>
<div>
    <button id="scroll-btn" class="chilli-btn float-end me-5" aria-label="Scroll to top">
        <i class="fas fa-arrow-up mx-auto my-auto"></i>
    </button>	
</div>

<!-- Return to top script -->
<script>
    const scrollBtn = document.getElementById("scroll-btn")
    scrollBtn.addEventListener("click", () => {
        window.scrollTo(0, 0)
    })
</script>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
{{ product }}
{% endblock %}

{% block content %}
<section class="container-fluid">
    <div class="row m-sm-4">
        <!-- Product image and description -->
        <div class="col-lg-6 text-center">
            <div>
                <h2 class="headings">{{ product }}</h2>
            </div>
            <div>
                {% if product.image %}
                    <img width="300" height="300" class="pics pics-lg" src="{{ product.image.url }}" alt="{{ product }}">
                {% else %}
                    <img width="300" height="300" class="pics pics-lg" src="{% static 'images/placeholder.png' %}" alt="No image available for {{ product }}">
                {% endif %}
            </div>
            <div class="text-contain">{{ product.description|linebreaks }}</div>
            {% if user.is_staff %}
            <div class="d-flex flex-row justify-content-evenly my-3">
                <!-- Edit and Delete for admin -->
                <a class="chilli-btn" href="{% url 'management:edit_product' product.pk %}">Edit Product</a>
                <a class="chilli-btn chilli-dngr" href="{% url 'management:delete_product' product.pk %}">Delete Product</a>
            </div>
            {% endif %}
        </div>
        <div class="col-lg-6 d-flex flex-column">
            <!-- Table for product details -->
            <div class="order-2 order-lg-1">
                <h2 class="headings headings-sm">{{ product }} Details:</h2>
                <table class="table table-borderless text-contain">
                    <tr>
                        <th>Category: </th>
                        <td>{{ product.category }}</td>
                    </tr>
                    {% if product.growth_time %}
                    <tr>    
                        <th>Growth time to maturity: </th>
                        <td>{{ product.growth_time }}</td>
                    </tr>
                    {% endif %}
                    {% if product.heat_level %}
                    <tr>    
                        <th>Heat: </th>
                        <td>{{ product.heat_level }}</td>
                    </tr>
                    {% endif %}
                    {% if product.ingredients %}
                    <tr>
                        <th>Ingredients: </th>
                        <td>{{ product.ingredients }}</td>    
                    </tr>
                    {% endif %}
                    {% if product.variants %}
                    <tr>
                        <th>Options: </th>
                        <td>
                            {% for variant in product.variants.all %}
                            <p class="mb-0">{{ variant.size }} - €{{ variant.price }}</p>
                            {% endfor %}
                        </td>
                    </tr>
                    {% endif %}
                    {% if product.box_contents.exists %}
                        {% if product.category.name == "Seedboxes" or product.category.name == "Sauceboxes" %}
                        <tr>
                            <th class="align-top">Contents: </th>
                            <td>{% for content in product.box_contents.all %}<p class="m-0">{{ content.name }}</p>
                                {% endfor %}</td>
                        </tr>
                        {% endif %}
                        {% if product.category.name == "Seeds" or product.category.name == "Sauces" %}
                        <tr>
                            <th class="align-top">Find in: </th>
                            <td>
                                {% for content in product.box_contents.all %}<p class="m-0">{{ content.name }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endif %}
                    {% endif %}
                    {% if avg_rating.rounded is not None %}
                    <tr>
                        <th>Avg. User Rating: </th>
                        <td>{% if avg_rating.rounded == 1 %}
                            <img width="33" height="80" class="rate-pics" src="{% static 'images/rate1.png' %}" alt="Rating">
                            {% elif avg_rating.rounded == 2 %}
                            <img width="63" height="80" class="rate-pics" src="{% static 'images/rate2.png' %}" alt="Rating">
                            {% elif avg_rating.rounded == 3 %}
                            <img width="93" height="80" class="rate-pics" src="{% static 'images/rate3.png' %}" alt="Rating">
                            {% elif avg_rating.rounded == 4 %}
                            <img width="124" height="80" class="rate-pics" src="{% static 'images/rate4.png' %}" alt="Rating">
                            {% else %}
                            <img width="154" height="80" class="rate-pics" src="{% static 'images/rate5.png' %}" alt="Rating">
                            {% endif %}
                            <strong>/</strong>
                            <img width="154" height="80" class="rate-pics" src="{% static 'images/rate5.png' %}" alt="Rating">
                        </td>
                    </tr>
                    {% endif %}
                </table>
            </div>
            <!-- Add to cart -->
            <div class="order-1 order-lg-2">
                <hr>
                <h3 class="headings big">Add To Cart:</h3>
                <form action="{% url 'cart:add_to_cart' product.id %}" method="POST">
                    {% csrf_token %}
                    <div>
                        <label class="me-4"><strong>Select Option:</strong></label>
                        <select name="product_variant" id="product_variant" class="border rounded-3" data-hx-get="/products/current_stock/" data-hx-target="#current_stock">
                            <option value="default">Please select an option...</option>
                            {% for variant in product.variants.all %}
                            <option data-variant_id="{{ variant.id }}" value="{{ variant.id }}">{{ variant.size }}
                                €{{ variant.price }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <p><strong>Stock: </strong> <span id="current_stock"></span></p>
                    <div class="my-3">
                        <label class="me-4"><strong>Select Quantity: </strong></label>
                        <div id="change_qty" class="d-inline">
                            <button type="button" id="dec_qty" class="chilli-btn" aria-label="Decrease quantity">-</button>
                            <input class="text-center" data-item_id="{{ product.id }}" name="quantity" id="product_qty"
                                type="number" value="1" min="0" max="99" aria-label="Quantity">
                            <button type="button" id="inc_qty" class="chilli-btn" aria-label="Increase quantity">+</button>
                            <p id="qty_warning"><em>No more available</em></p>
                        </div>
                    </div>
                    {% if not user.is_authenticated %}
                    <p class="small">If you have an account please <a class="chilli-link" href="{% url 'account_login' %}">login</a> before you start shopping for the best experience.</p>
                    {% endif %}
                    <button id="add" class="chilli-btn my-2 d-block" type="submit" disabled>Add To Cart</button>
                </form>
                {% for item in cart_items %}
                    {% if forloop.first %}
                        {% if product.id == item.product.id %}
                            <p class="small">{{ product }} already in cart.</p>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <hr>
    </div>
    <div class="row">
        <!-- Reviews -->
        <div class="col-12">
            <h2 class="headings">Reviews</h2>
            {% if reviewed %}
            <p><strong>Thank you for your review! If you'd like to get in touch with any concerns, please visit our <a
                        class="chilli-link" href="{% url 'home:contact' %}">contact page</a>.</strong></p>
            {% else %}
            <!-- Review form -->
            <h3>Write a review for {{ product }}:</h3>
            <p><strong>Or if you would like to get in touch with any concerns, please visit our <a
                class="chilli-link" href="{% url 'home:contact' %}">contact page</a>.</strong></p>
            <form class="col-lg-4 mb-5" method="post">
                {% csrf_token %}
                {{ review_form | crispy }}
                <p>Posting as: {% if user.is_authenticated %}{{ user }}{% else %}Anonymous{% endif %}</p>
                <button type="submit" class="chilli-btn">Submit</button>
            </form>
            {% endif %}
            <div class="row">
                <!-- User reviews -->
                {% for review in reviews %}
                <div class="col-sm-6 col-lg-4 mb-5 px-sm-3">
                    <div class="card px-3">
                        <h2 class="headings big">
                            {% if review.reviewer is not None %}{{ review.reviewer.display_name }}{% else %}Anonymous{% endif %} <span
                                class="small">on {{ review.added_on|date:'d/m/y' }}</span></h2>
                        <p>{{ review }}</p>
                        <p><strong>Rating: </strong>
                            {% if review.rating == 1 %}
                            <img width="33" height="80" class="rate-pics" src="{% static 'images/rate1.png' %}" alt="Rating">
                            {% elif review.rating == 2 %}
                            <img width="63" height="80" class="rate-pics" src="{% static 'images/rate2.png' %}" alt="Rating">
                            {% elif review.rating == 3 %}
                            <img width="93" height="80" class="rate-pics" src="{% static 'images/rate3.png' %}" alt="Rating">
                            {% elif review.rating == 4 %}
                            <img width="124" height="80" class="rate-pics" src="{% static 'images/rate4.png' %}" alt="Rating">
                            {% else %}
                            <img width="154" height="80" class="rate-pics" src="{% static 'images/rate5.png' %}" alt="Rating">
                            {% endif %}
                        </p>
                            <div class="d-flex flex-row justify-content-between my-2">
                                {% if user.is_authenticated and user.userprofile == review.reviewer %}
                                    <a class="chilli-btn chilli-go" href="{% url 'profiles:edit_review' review.pk %}">Edit Review</a>
                                {% endif %}
                                {% if user.is_staff or user.is_authenticated and user.userprofile == review.reviewer %}
                                    <a class="chilli-btn chilli-dngr" href="{% url 'management:remove_review' review.pk %}">Delete Review</a>
                                {% endif %}
                            </div>
                    </div>
                </div>
                {% empty %}
                    {% if not reviewed %}
                        <p><strong>No reviews yet. Be the first to write one!</strong></p>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block additional_script %}
<script src="{% static 'js/product.js' %}"></script>
{% endblock %}